name: QA
on: [ merge_group, push, pull_request ]
jobs:
  flake-check:
    name: Nix Flake Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Nix Flake Checks
        run: nix flake check --all-systems
