name: QA
on: [ pull_request ]
jobs:
  flake-check:
    name: Nix Flake Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Nix Flake Checks
        run: nix flake check --all-systems
  nixos-tests:
    runs-on: large_runner_16core_64gb
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Basic setup
        run: |
          nix build .#tests.x86_64-linux.openstack-default-setup.driver
          ./result/bin/nixos-test-driver
      - name: Live migration
        run: |
          nix build .#tests.x86_64-linux.openstack-live-migration.driver
          ./result/bin/nixos-test-driver
